kicad-cli: Register --include-excluded-from-bom argument
ea904c9f introduced a new cli argument to `kicad-cli sch export bom`,
but it did not actually register it with the argument parser.  Any
invocation of `kicad-cli sch export bom` currently results in this
error:

  Error: Unhandled exception class: St11logic_error  what: No such
argument: --include-excluded-from-bom

This patch adds the registration.

Fixes https://gitlab.com/kicad/code/kicad/-/issues/19335